{% set name = "coxeter" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce85dbe203e6d2f2278094592c2c293791295d257124db2caa779a8406ab1a40

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.10
    - scipy
    - rowan

test:
  imports:
    - coxeter
    - coxeter.shapes
    - coxeter.families

about:
  home: https://github.com/glotzerlab/coxeter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for creating and manipulating shapes.

  description: |
    coxeter is used for working with polytopes and other shapes.
    The package is focused on providing robust methods for computing
    standard geometric quantities, particularly for polytopes where
    implementing such calculations for generic shapes requires care
    to properly handle convexity, proper vertex ordering, and other
    related issues.
  doc_url: http://coxeter.readthedocs.io/
  dev_url: https://github.com/glotzerlab/coxeter

extra:
  recipe-maintainers:
    - DomFijan
    - janbridley
    - joaander
    - vyasr
    - Tobias-Dwyer
