{% set name = "coxeter" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af38542c7280d707931cb1aad795323e465518f1c5476af5929f770eda30e816

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.10
    - scipy
    - rowan

test:
  requires:
    - python {{ python_min }}
  imports:
    - coxeter
    - coxeter.shapes
    - coxeter.families

about:
  home: https://github.com/glotzerlab/coxeter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for creating and manipulating shapes.

  description: |
    coxeter is used for working with polytopes and other shapes.
    The package is focused on providing robust methods for computing
    standard geometric quantities, particularly for polytopes where
    implementing such calculations for generic shapes requires care
    to properly handle convexity, proper vertex ordering, and other
    related issues.
  doc_url: http://coxeter.readthedocs.io/
  dev_url: https://github.com/glotzerlab/coxeter

extra:
  recipe-maintainers:
    - DomFijan
    - janbridley
    - joaander
    - vyasr
    - Tobias-Dwyer
